### ISSUE TITLE
Base de Dados para os Fatos

### ISSUE THREAD

**Issue by Rocsantos** [UnBParadigmas2023-2/2023.2_G1_Logico#2]
Para está base de dados vamos precisar de:

## Disciplinas
- [x] Código da disciplina
- [x] Nome da disciplina 
- [x] Disciplina pré-requisito
- [x] Disciplina obrigatória

## Professor
- [x] Nome
- [x] Disciplina
- [x] Horários da disciplina

**Comment by roddas** [comment]
Atualmente existem base de dados para:

- matérias obrigatórias
- matérias optativas
- atividades complementares que compreendem: estágio,pibic, trabalho, unb idiomas e outros.


Alguma coisa em falta até aqui ?
